import { useEffect, useMemo, useRef, useState } from "react"
import { read, utils } from "xlsx"
import { toast } from "react-toastify"
import { HiOutlineCloudUpload, HiOutlineDocumentText, HiOutlineDownload, HiOutlineSearch } from "react-icons/hi"
import { downloadPriorityOneReport, importUnifastRecords, listPriorityRecords } from "../services/priorityOneService"

const normalizeId = (value) => String(value || "").replace(/\D/g, "")
const studentData = (row) => row?.data || row || {}
const studentId = (row) => normalizeId(row?.id || studentData(row).studentId || studentData(row).studentnumber)
const studentName = (row) => { const data = studentData(row); return data.fullName || [data.fname, data.mname, data.lname].filter(Boolean).join(" ") || "-" }

function mapExcelRow(row = {}) {
	const entries = Object.entries(row); const find = (...patterns) => entries.find(([key]) => patterns.some((pattern) => key.toLowerCase().includes(pattern)))?.[1]
	return { studentId: find("student id", "student number", "student no"), studentName: find("student name", "full name", "name"), course: find("course", "program"), yearLevel: find("year level", "year"), startYear: find("start year", "entry year"), yearsUsed: find("years used"), academicCycle: find("academic cycle", "school year") }
}

export default function AdminUnifastManagement({ students = [] }) {
	const inputRef = useRef(null); const [records, setRecords] = useState([]); const [tab, setTab] = useState("with"); const [search, setSearch] = useState(""); const [eligibleOnly, setEligibleOnly] = useState(false); const [uploading, setUploading] = useState(false)
	const load = async () => { const result = await listPriorityRecords("unifast_records"); setRecords(result.records || []) }
	useEffect(() => { load().catch(() => toast.error("UNIFAST records could not be loaded.")) }, [])
	const withIds = useMemo(() => new Set(records.filter((item) => item.matchedStudent).map((item) => normalizeId(item.studentId))), [records])
	const rows = useMemo(() => { const source = tab === "with" ? records : students.filter((row) => !withIds.has(studentId(row))).map((row) => ({ id: studentId(row), studentId: studentId(row), studentName: studentName(row), course: studentData(row).course, yearLevel: studentData(row).year, eligible: true, matchedStudent: false })); return source.filter((item) => !eligibleOnly || item.eligible !== false).filter((item) => `${item.studentId} ${item.studentName} ${item.course}`.toLowerCase().includes(search.toLowerCase())) }, [eligibleOnly, records, search, students, tab, withIds])
	const upload = async (file) => { if (!file) return; setUploading(true); try { const workbook = read(await file.arrayBuffer(), { type: "array" }); const parsed = utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], { defval: "" }).map(mapExcelRow); const result = await importUnifastRecords({ records: parsed, actorId: sessionStorage.getItem("bulsuscholar_userId") || "admin" }); toast.success(`${result.savedCount} UNIFAST records imported.`); await load() } catch (error) { toast.error(error.message || "UNIFAST import failed.") } finally { setUploading(false); if (inputRef.current) inputRef.current.value = "" } }
	const exportReport = async (format) => { const headers = ["Student ID", "Student Name", "Course", "Year Level", "Years Used", "Eligibility"]; const reportRows = rows.map((item) => [item.studentId, item.studentName, item.course || "-", item.yearLevel || "-", item.yearsUsed ?? "-", item.eligible === false ? "Ineligible" : "Eligible"]); await downloadPriorityOneReport(format, { filename: `unifast-${tab}.${format === "excel" ? "xlsx" : "pdf"}`, title: "UNIFAST Student Report", headers, rows: reportRows }) }
	return <section className="admin-feature-page"><header className="admin-feature-header"><span><HiOutlineDocumentText /></span><div><h2>UNIFAST Management</h2><p>Match imported UNIFAST records to students and monitor five-year eligibility.</p></div><div className="admin-feature-header-actions"><input ref={inputRef} type="file" hidden accept=".xlsx,.xls,.csv" onChange={(event) => upload(event.target.files?.[0])} /><button onClick={() => inputRef.current?.click()} disabled={uploading}><HiOutlineCloudUpload />{uploading ? "Importing..." : "Import Excel"}</button><button onClick={() => exportReport("pdf")}><HiOutlineDownload /> PDF</button><button onClick={() => exportReport("excel")}><HiOutlineDownload /> Excel</button></div></header><div className="admin-feature-stats"><div><span>Imported Records</span><strong>{records.length}</strong></div><div><span>Matched Students</span><strong>{records.filter((item) => item.matchedStudent).length}</strong></div><div><span>Five-Year Ineligible</span><strong>{records.filter((item) => item.eligible === false).length}</strong></div></div><div className="admin-feature-tabs"><button className={tab === "with" ? "active" : ""} onClick={() => setTab("with")}>With UNIFAST</button><button className={tab === "without" ? "active" : ""} onClick={() => setTab("without")}>Without UNIFAST</button></div><div className="admin-feature-filters"><label><HiOutlineSearch /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search student ID, name, or course" /></label><label className="admin-feature-checkbox"><input type="checkbox" checked={eligibleOnly} onChange={(event) => setEligibleOnly(event.target.checked)} /> Eligible only</label></div><div className="admin-feature-table-wrap"><table className="admin-feature-table"><thead><tr><th>Student ID</th><th>Student Name</th><th>Course</th><th>Year</th><th>Years Used</th><th>Match</th><th>Eligibility</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id || item.studentId}><td>{item.studentId}</td><td title={item.studentName}>{item.studentName}</td><td title={item.course}>{item.course || "-"}</td><td>{item.yearLevel || "-"}</td><td>{item.yearsUsed ?? "-"}</td><td>{item.matchMethod === "name_similarity" ? "Name similarity" : item.matchedStudent ? "Student ID" : "Not imported"}</td><td><span className={`leave-status ${item.eligible === false ? "rejected" : "approved"}`}>{item.eligible === false ? "5-year limit" : "Eligible"}</span></td></tr>)}</tbody></table>{!rows.length ? <div className="portal-empty">No records match this view.</div> : null}</div></section>
}
